[models]
#chat                = "gemma3:1b"
chat                = "ministral_3b:latest"
#chat                = "mistral:7b-instruct-v0.2-q4_K_M"
memory              = "nomic-embed-text"
project_manager     = "gemma3:1b"

# chat_max_tokens     =
# pm_max_tokens       =

[load_system_prompt]
chat            = "system"
# memory          = "memory"
# project_manager = "project_manager"

# [ollama]
# url = "http://localhost:11434"

[memory]
retrieve_entry_limit                        = 3
auto_memory_store_enable_at_model_tokens    = 128000
enable_auto_memory_retrieve                 = true
enable_auto_memory_store                    = true

[file_reader]
auto_read_dropbox_enable_at_model_tokens    = 128000
enable_auto_read_dropbox                    = true
docling_default                             = true

[search]
engine                                  = "http://localhost:8080/search"
max_results                             = 3
max_char_per_page                       = 3000
auto_web_search_enable_at_model_tokens  = 128000
enable_auto_web_search                  = true

