import sys
from pathlib import Path

from config import BASE_DIR, DEFAULT_PATH, STORE_PATH, BASE_PROJECT_DIR_PATH
from agent import Agent, LLM, Memory

TEST_MODEL = "gemma3:1b"
DEBUG_TEST_CHAT = "debug_test"
TEST_PATH = STORE_PATH / f"{DEBUG_TEST_CHAT}.json"
TEST_DIR = Path(__file__).parent
PDF = TEST_DIR / "test" / "test.pdf"


# -- local functions -------------------------------------------------------


def _clear_chat(TEST_PATH):
    print(f"Cleaning up: Removing {TEST_PATH}...")
    if TEST_PATH.exists():
        TEST_PATH.unlink()
        print(f"{TEST_PATH} has been removed")
        return
    print(f"Error: {TEST_PATH} not found")


# -- agent -----------------------------------------------------------------


def LLM_test():
    print("---------------------------------------------------------")
    print("                 Manually testing LLM                    ")
    print("                                                         ")
    print("- Message the model directly without using the Agent.    ")
    print("---------------------------------------------------------")
    message = LLM.user("Say hello.")
    print()
    print(f"Messaging model: {message}")
    print("response:")
    print(f">>>{LLM.model_response([message], model=TEST_MODEL)}")
    print()
    print("<<< OK >>>\n")


def Memory_test():
    print("---------------------------------------------------------")
    print("                      Memory test                        ")
    print("                                                         ")
    print("- Check if memory functional without calling the MODEL.  ")
    print("---------------------------------------------------------")
    memory = Memory(session=DEBUG_TEST_CHAT)
    # -- messages to memory --
    send = "Hello."
    reply = "Hi there."
    print()
    print(f"Send: {send}")
    memory.chat_update("user", f"{send}")
    print(f"Reply: {reply}")
    memory.chat_update("assistant", f"{reply}")
    # -- show history to the terminal --
    print("Retrieving history...")
    print()
    print("history:")
    print(f">>>{memory.get()}")
    print()
    print("<<< OK >>>\n")
    # -- clean up --
    _clear_chat(TEST_PATH)
    print()


def Agent_test():
    print("---------------------------------------------------------")
    print("                     Agent test                          ")
    print("---------------------------------------------------------")
    agent = Agent(model=TEST_MODEL, session=DEBUG_TEST_CHAT)
    question = "What is python? Answer in one sentence only."
    print()
    print(f"Asking Agent: {question}")
    print("Agent response:")
    print(f">>>{agent.ask(question)}")
    print()
    print("<<< OK >>>\n")
    # -- clean up --
    _clear_chat(TEST_PATH)
    print()


# -- tools ----------------------------------------------------------------


def PDF_test():
    print("---------------------------------------------------------")
    print("                     PDF reader test                     ")
    print("---------------------------------------------------------")
    agent = Agent(model=TEST_MODEL, session=DEBUG_TEST_CHAT)
    memory = Memory(session=DEBUG_TEST_CHAT)
    from tools import Reader

    reader = Reader(session=DEBUG_TEST_CHAT)
    question = "What is in the document?"
    messages = reader.read_file(PDF, question)
    print("context:")
    print(f">>>{messages}")
    print()
    print("response:")
    print(f">>>{agent.ask(question, messages)}")
    print()
    print("chat history:")
    print(f">>>{memory.get()}")
    print()
    print("<<< OK >>>\n")
    # -- clean up --
    _clear_chat(TEST_PATH)
    print()


def Search_test():
    print("---------------------------------------------------------")
    print("                     Search test                         ")
    print("                                                         ")
    print("Search flag return two values:                           ")
    print("1. Response to the user in the chat.                     ")
    print("2. Summary of the search results generated by the model. ")
    print("---------------------------------------------------------")
    from tools import Search

    query = "Date"
    question = "What is today's date?"
    print(f"Query: {query}")
    print(f"Question: {question}")
    print("Searching...")
    answer, summary = Search.web(query, question)
    print("Response:")
    print(f">>>{answer[:200]}")
    print()
    print("Summary:")
    print(f">>>{summary[:200]}")
    print()
    print("<<< OK >>>\n")
    print()


# -- run ------------------------------------------------------------------


def run_all():
    tests = [LLM_test, Memory_test, Agent_test, PDF_test]
    for test in tests:
        try:
            test()
        except Exception as e:
            print(f"TEST FAILED: {e}\n")


if __name__ == "__main__":
    print("Initiating debuging script...")
    print("+--------------------------------+")
    print(f"+ Model:     {TEST_MODEL}        ")
    print(f"+ Test path: {DEBUG_TEST_CHAT}   ")
    print("+--------------------------------+")
    print()
    run_all()
